### ISSUE TITLE
Unhandled Exception: Cannot get size of inactive element.

### ISSUE THREAD

**Issue by soc221b** [ayham95/Measured-Size#4]
Hi, thanks for useful widget.

After delayed, we need to check whether it is mounted:

https://github.com/ayham95/Measured-Size/blob/3204ecbe2083732bb59c736803897bcf58b3753e/lib/measured_size.dart#L50

**Comment by techouse** [comment]
It's addressed in this PR https://github.com/ayham95/Measured-Size/pull/5
